name: test-suite

on:
  push:
    branches: [main]
  pull_request:
    branches:
    - main
    - 'releases/**'
  schedule:
    - cron: '30 22 * * 0,3'
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [gcc-14, clang-18]
        include:
          - c_compiler: gcc-14
            compiler: gcc-14
          - cxx_compiler: g++-14
            compiler: gcc-14
          - c_compiler: clang-18
            compiler: clang-18
          - cxx_compiler: clang++-18
            compiler: clang-18
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2

      - name: configure
        run: |
          cd test
            cmake -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
                  -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} \
                  -B build

      - name: build
        run: cd test && cmake --build build

      - name: test
        run: cd test/build && ctest --output-on-failure
